name: bacteria
description: bacteria
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  bloc_concurrency: ^0.2.1
  flutter:
    sdk: flutter
  logger: ^1.2.2
  uuid: ^3.0.7
  go_router: ^6.2.0
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.18
  flutter_launcher_icons: ^0.12.0
  flutter_gen: ^5.2.0
  flutter_gen_runner: ^5.2.0
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1
flutter:
  uses-material-design: true